### ISSUE TITLE
Avoid mutexes for low latency code

### ISSUE THREAD

**Issue by quizac-** [apmastering/APComp#5]
I noticed this line:
std::lock_guard<std::mutex> lock(oversamplingMutex);

Mutexes are cheap but there is no free lunch. Depending on implementation it may cause context switch flushing MMU’s TLB pages and recreating them is expensive. It may also flush all superpipelines on all CPU cores to make sure there is only one thread to write or read from it. It may cause unnecessary delays under extreme conditions. Locking should be avoided in low latency applications.
I propose to replace it with 2 volatile variables. OversamplingSettable where GUI writes to it. The 2nd variable OversamplingCopy would copy value from the above at the beginning of each loop or when necessary and use it locally until whole block is processed.

**Comment by apmastering** [comment]
Mutex now removed. Thanks for the observation. I stuck with the juce oversampling in the end. Couldn't make my bespoke code work better than the juce implementation.

**Comment by quizac-** [comment]
Hi,

It’s me again:) Perhaps l’m being too anal about it bc I tend to code low latency applications in C for DPDK framework to receive, mangle and forward millions packets per second on x64 platform where every bit of code has to have predictable path and do no harm to other threads. Also, the fact that I really like your project, efforts and YT videos. You are trying your best to provide excellent value to community similarly to Chris from AirWindows(great ToTape7 plugin and others available on github too).
So, usually, atomics in C/C++ on x64 platform are wrapped by compiler with lfence or mfence instructions or both to ensure there is only one thread adjusting variable at the same time. This causes tiny “hiccup” on all cores especially visible on 8+ threads hence many programmers tend to focus on lockless implementations to avoid it. 
You may consider adding settable variable declared as “volatile” - this will force compiler to write it directly to RAM skipping all CPU cashes(no delay). Unless I’m wrong, due to the nature of this app, this variable doesn’t have to be consistent on all threads all the time. It just has to ensure that it doesn’t change during loop run. Volatile variable set by one GUI thread can be changed immediately in memory and copied as temporary variable at the beginning of each loop to be used til end of it.

Kind regards,
Marcin

**Comment by apmastering** [comment]
This is a fantastic point and I've researched it more and I understand much better now the problems and solutions. Thank you. My coding background is in web and financial programming in python, so my skill with multiple threads is quite bad seeing as I've rarely worked with multiple threads at all in the past and when I have it's with python libraries and this low level detail is basically hidden in python. However, I'm going to improve this right now. I'm working on a much more complex plugin which will be paid but also a free version, and many of the mistakes I made and solutions I have learned are going into this new plugin. I will definitely be making more plugins both free and paid so I highly value your excellent input!

**Comment by apmastering** [comment]
All locks from my code are now gone. HOWEVER the way the JUCE framework handles parameters is absolutely full with `std::atomic<float> ` and I have found that simply getting the raw parameter values from JUCE's parameters is relatively expensive. For sensible plugin automation, you need to do this at least once per block in the audio thread. So I'm considering an approach of starting a worker thread from the audio thread to go off and collect all the parameters but I fear that the overhead of starting the new thread will probably be bigger than the cost of recaching the knob values. I guess this is just a limitation of the JUCE framework.
